[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200

[[redirects]]
  from = "/api/auth/logout"
  to = "/.netlify/functions/auth-logout"
  status = 200

[[redirects]]
  from = "/api/notes/:id"
  to = "/.netlify/functions/notes-detail/:id"
  status = 200

[[redirects]]
  from = "/api/notes"
  to = "/.netlify/functions/notes"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
